# Generated by Django 6.0 on 2025-12-14 20:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Слаг')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='categories/', verbose_name='Изображение')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Слаг')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Цена')),
                ('unit', models.CharField(choices=[('g', 'Граммы'), ('kg', 'Килограммы'), ('ml', 'Миллилитры'), ('l', 'Литр'), ('pcs', 'Штуки'), ('pack', 'Упаковка')], max_length=10, verbose_name='Единица измерения')),
                ('weight_per_unit', models.DecimalField(decimal_places=3, help_text='Например: 100 для 100г, 0.5 для 500мл', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Вес/объем на единицу')),
                ('image', models.ImageField(blank=True, upload_to='ingredients/', verbose_name='Изображение')),
                ('available', models.BooleanField(default=True, verbose_name='В наличии')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Количество на складе')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='products.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['id', 'slug'], name='products_in_id_47e5cc_idx'), models.Index(fields=['name'], name='products_in_name_948de3_idx'), models.Index(fields=['-created'], name='products_in_created_133787_idx')],
            },
        ),
    ]
