# Generated by Django 6.0 on 2025-12-14 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reported_by',
            field=models.ManyToManyField(blank=True, related_name='reported_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пожаловались'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['ingredient', 'created'], name='reviews_rev_ingredi_1983f6_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user', 'created'], name='reviews_rev_user_id_d4b7bb_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['is_hidden'], name='reviews_rev_is_hidd_9409fe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'ingredient')},
        ),
    ]
